# //Numpy Practise//

In [1]:
import numpy as np

In [2]:
myarr =np.array([[1,54,68,48]],np.int8)

In [3]:
myarr[0,1]

54

In [4]:
myarr[0,1]=22

In [5]:
myarr

array([[ 1, 22, 68, 48]], dtype=int8)

In [6]:
myarr.shape

(1, 4)

In [7]:
myarr.dtype

dtype('int8')

# Array creation: Conversion From other Python structures

In [8]:
listarray = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [9]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
listarray.dtype

dtype('int32')

In [11]:
listarray.shape

(3, 3)

In [12]:
listarray.size

9

In [13]:
np.array({21,47,98})

array({98, 21, 47}, dtype=object)

In [14]:
zeros= np.zeros((2,5))

In [15]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
rng = np.arange(15)

In [17]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [18]:
lspace = np.linspace(1,5,12)

In [19]:
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [20]:
emp =np.empty((4,6))

In [21]:
emp

array([[1.04427870e-311, 1.04428159e-311, 1.04427870e-311,
        1.04427870e-311, 1.04428159e-311, 1.04427870e-311],
       [1.04428159e-311, 1.04427870e-311, 1.04427870e-311,
        1.04428159e-311, 1.04427870e-311, 1.04428159e-311],
       [1.04427870e-311, 1.04427870e-311, 1.04428159e-311,
        1.04427870e-311, 1.04428159e-311, 1.04427870e-311],
       [1.04427870e-311, 1.04428159e-311, 1.04427870e-311,
        1.04428159e-311, 1.04427870e-311, 1.04428159e-311]])

In [22]:
emp_like= np.empty_like(lspace)

In [23]:
emp_like

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [24]:
ide = np.identity(45)

In [25]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [26]:
ide.shape

(45, 45)

In [27]:
arr = np.arange(99)

In [28]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [29]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [30]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

# Axis in numpy

In [31]:
x= [[1,2,3],[4,5,6],[7,1,0]]

In [32]:
ar=np.array(x)

In [33]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [34]:
ar.sum(axis=0)

array([12,  8,  9])

In [35]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [36]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [37]:
ar.flat

In [38]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [39]:
ar.ndim

2

In [40]:
ar.size

9

In [41]:
one=np.array([1,3,4,652,1])

In [42]:
one.argmax()

3

In [43]:
one.argmin()

0

In [44]:
one.argsort()

array([0, 4, 1, 2, 3], dtype=int64)

In [45]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [46]:
ar.argmin()

8

In [47]:
ar.argmax()

6

In [48]:
ar.argmax(axis=0)

array([2, 1, 1], dtype=int64)

In [49]:
 ar.argmax(axis=1)

array([2, 2, 0], dtype=int64)

In [50]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [51]:
ar.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]], dtype=int64)

In [52]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [53]:
ar.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

In [54]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [55]:
ar2= np.array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [56]:
ar+ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [57]:
ar*ar2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [58]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [59]:
ar.sum()

29

In [60]:
ar.max()

7

In [61]:
ar.min()

0

In [62]:
np.where(ar>5)

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [63]:
np.count_nonzero(ar)

8

In [64]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))

In [65]:
ar[1,2]=0

In [66]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 0, 1], dtype=int64))

In [67]:
import sys

In [68]:
py_ar=[0,4,55,2]

In [69]:
np_ar=np.array(py_ar)

In [70]:
sys.getsizeof(1)*len(py_ar)

112

In [71]:
np_ar.itemsize * np_ar.size

16